SELECT PLAYER_ID , PLAYER_NAME , BACK_NO , 
		TEAM_ID
		FROM (
			SELECT PLAYER_ID , PLAYER_NAME , BACK_NO , 
					TEAM_ID, ROW_NUMBER () OVER(ORDER BY PLAYER_ID) RN 
				FROM PLAYER p
				) 
		WHERE RN BETWEEN 1 AND 10;
			
SELECT COUNT(*)
	FROM PLAYER p 
	WHERE TEAM_ID = 'K01';
	
SELECT PLAYER_ID , PLAYER_NAME , BACK_NO , 
		TEAM_ID
		FROM (
			SELECT PLAYER_ID , PLAYER_NAME , BACK_NO , 
					TEAM_ID, ROW_NUMBER () OVER(ORDER BY PLAYER_ID) RN 
				FROM PLAYER p
				WHERE TEAM_ID = 'K01'
				) 
		WHERE RN BETWEEN 1 AND 10;
		
SELECT *
	FROM PLAYER p 